name: Deploy Frontend App

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install  # Only needed if you use a package.json file

      - name: Build Project (Optional)
        run: npm run build  # Skip if there's no build step

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to GitHub Pages
          folder: dist  # Change to your build folder (if any)
          
